name: tyto-api

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    networks:
      - tyto-internal
    restart: unless-stopped

  api:
    build: .
    container_name: tyto-api
    depends_on:
      - influxdb
    ports:
      - "8000:8000"
    networks:
      - tyto-internal
      - proxy-net
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy-net"
      - "traefik.http.routers.tyto-api.rule=Host(`weather-api.owl-nest.ch`)"
      - "traefik.http.routers.tyto-api.entrypoints=web"
      - "traefik.http.services.tyto-api.loadbalancer.server.port=8000"

volumes:
  influxdb-data:
    external: true
    name: tyto_influxdb-data
  influxdb-config:
    external: true
    name: tyto_influxdb-config

networks:
  proxy-net:
    external: true
  tyto-internal:
